"""Core services: file handling, memory, storage, response formatting."""

from services.core.attachment_storage import (
    StoredAttachment,
    save_upload,
    ensure_storage_directory,
)
from services.core.file_parser import (
    ParsedAttachment,
    AttachmentError,
    parse_attachment,
)
from services.core.chat_memory import (
    query_tokens,
    has_context_reference,
    detect_task_number,
    detect_topic,
    looks_like_task_set,
    update_state_dict,
    build_memory_summary,
    load_session_state,
    persist_session_state,
    load_context_messages,
    session_attachments,
    select_relevant_attachments,
    attachment_inventory,
    build_attachment_context,
    message_attachments_payload,
)
from services.core.response_formatter import (
    format_for_telegram,
    telegram_safe_text,
    canonicalize_message,
    contains_raw_latex,
    normalize_latex_transport,
    telegram_parts,
    render_formula_png,
    MATH_FORMATTING_RULES,
    TelegramPart,
)

__all__ = [
    "StoredAttachment",
    "save_upload",
    "ensure_storage_directory",
    "ParsedAttachment",
    "AttachmentError",
    "parse_attachment",
    "query_tokens",
    "has_context_reference",
    "detect_task_number",
    "detect_topic",
    "looks_like_task_set",
    "update_state_dict",
    "build_memory_summary",
    "load_session_state",
    "persist_session_state",
    "load_context_messages",
    "session_attachments",
    "select_relevant_attachments",
    "attachment_inventory",
    "build_attachment_context",
    "message_attachments_payload",
    "format_for_telegram",
    "telegram_safe_text",
    "canonicalize_message",
    "contains_raw_latex",
    "normalize_latex_transport",
    "telegram_parts",
    "render_formula_png",
    "MATH_FORMATTING_RULES",
    "TelegramPart",
]
